spring.datasource.url:  jdbc:mysql://localhost:3306/diploma?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 14101410
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false
spring.freemarker.expose-request-attributes: true


blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 911 572-92-48
blog.email: leshak549@gmail.com
blog.copyright: Дмитрий Сергеев
blog.copyrightForm: 2005
